// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBEEEy1vdyeI7bWAfQ8B3kWwH6xpfYTeI',
    appId: '1:976714035962:web:dc072ac4d07e76a5b38f43',
    messagingSenderId: '976714035962',
    projectId: 'infisocial-90d8b',
    authDomain: 'infisocial-90d8b.firebaseapp.com',
    storageBucket: 'infisocial-90d8b.firebasestorage.app',
    measurementId: 'G-XP6PES1BZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3ZGMwM9tGOW5J4s4jfS_5dhOJBy4sds',
    appId: '1:976714035962:android:7d197f1b7b01fd5ab38f43',
    messagingSenderId: '976714035962',
    projectId: 'infisocial-90d8b',
    storageBucket: 'infisocial-90d8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYi-3TnDnioAJAARCwziKCTAsYfY-gtS0',
    appId: '1:976714035962:ios:23ccd59e0af84a30b38f43',
    messagingSenderId: '976714035962',
    projectId: 'infisocial-90d8b',
    storageBucket: 'infisocial-90d8b.firebasestorage.app',
    iosBundleId: 'com.example.infiSocial',
  );
}
